# configs/exp/vdn_smacv2.yaml — placeholder until custom wrappers are ready.
algo: vdn
env: sc2v2
with:
  seed: 1
  env_args.map_name: "protoss_5_vs_5"
  common_reward: false
  t_max: 2000000
  batch_size: 32
wandb:
  project: MARL-EPy
  group: vdn-smacv2
