# QMIX + SMAC 3s5z 실험 (RNN + last action 활성화)
algo: vdn
env_config: sc2
wandb_config: smac1
with:
  env_args.map_name: "3s_vs_5z"
  env_args.difficulty: "7"
  env_args.state_last_action: true
  env_args.reward_scale: false
  use_rnn: true
  obs_last_action: true
  epsilon_anneal_time: 100000
  epsilon_finish: 0.05
